//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public Nullable<int> RestaurantID { get; set; }
        public string username { get; set; }
        public int alevel { get; set; }
        public string pwd { get; set; }
        public string email { get; set; }
    }
}
