//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int DealId { get; set; }
        public int RestaurantId { get; set; }
        public string Title { get; set; }
        public string Descript { get; set; }
        public Nullable<int> category { get; set; }
        public bool Priority { get; set; }
    }
}
