//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int RestaurantId { get; set; }
        public string Address { get; set; }
        public string Name { get; set; }
        public Nullable<int> NoOfTables { get; set; }
    }
}
