//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaitingParty
    {
        public int PartyId { get; set; }
        public Nullable<int> RestaurantID { get; set; }
        public int NoOfGuests { get; set; }
    }
}
